### ISSUE TITLE
grunt dev -- Task not found

### ISSUE THREAD

**Issue by JeffLoo-ong** [solidusjs/solidus#148]
Looks like this isn't registered as a task in the Grunt.js file. 

Sass is also not building properly due to not being able to find the path.

**Comment by joanniclaborde** [comment]
Which Grunt.js file? Are you sure you're on the right repo?

**Comment by JeffLoo-ong** [comment]
Ack, I was looking at the solidus template repo! Sorry wrong place :( Closing this.
