### ISSUE TITLE
Ability to request a single resource with AJAX

### ISSUE THREAD

**Issue by Fauntleroy** [solidusjs/solidus#48]
Sure would be awesome if I could somehow just request a single resource from a page for use with AJAX. I figure something simple like the following could work: `/news/5.json?resource=posts`. Then the page would know to just request the one resource and only return json. The problems I see with this approach are:

- The `resource` query parameter might be used by someone. We could always just use something like `_resource` or make it configurable
- Preprocessors might expect other resources on the page to exist, causing them to throw errors.

We could get around the latter problem in a couple ways. First, we could just request the resource without invoking any preprocessors. This doesn't seem like a great choice to me, since I'm already using resources with preprocessors all over the place, but at least we'd avoid errors. Another idea is to separate resources from pages, then we can request them directly. This would require some major rethinking when it comes to preprocessors, and it would invariably prevent preprocessors from using the page context.

I can't think of any great solutions right now, but this is something that really needs to happen for AJAX to be a good option in Solidus sites.

**Comment by joanniclaborde** [comment]
Fixed by solidus-client
